### PR TITLE
Core files formatted for readability.

### PR DESCRIPTION
**Pull request by Katamori**
Not sure, how or where did you make those CSS and JS files, but their uglified forms were essentially unreadable.

Any change on the code is impossible this way.

Sadly I could not make a PR to a branch that isn't existing yet, but of course I'm not expecting you to add it to master. If possible, put it to a new branch, or simply refuse if there's any reason not to format those files this way.

### CODE REVIEW

**Comment by skzap** [comment]
These files are generated by meteor (the framework we use). The repository is not meant to be edited like that, it should just be a dump of minified files to serve for production. The unminified code is in another repository, currently private, but that will be in our GitHub soon (in 1 or 2 patch most likely)

**Comment by Katamori** [comment]
Yeah, I had a similar assumption.

I was just a bit too excited to wait ^^"

**Comment by jonasfranz** [comment]
@skzap Any updates on this:
> The unminified code is in another repository, currently private, but that will be in our GitHub soon (in 1 or 2 patch most likely)

**Comment by Katamori** [comment]
@JonasFranzDEV no, we're still waiting.

But I'm sure he has a very good reason.

**Comment by erri120** [comment]
@Katamori I was just about to do the same. I hope we can work on the repository soon.

**Pull request closed without merging**
